### ISSUE TITLE
Can't quit from listing mode in case of "no data" filter

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/LightPivotTable#10] opened 2017-07-23 07:20 UTC
If the filter results in now rows LPT switches into "no rows" mode and never back.
Reproduce here:
http://146.185.143.59/dsw/index.html#!/d/Date%20Filter%20Demo.dashboard?ns=SAMPLES#%2F%3Fns=SAMPLES
![lptlistingbug](https://user-images.githubusercontent.com/2781759/28497450-22668cca-6f90-11e7-8c6d-9a9792faac18.gif)

Another strange but similar thing can be reproduced here:
https://analytics.community.intersystems.com/dswpub/index.html#!/d/Public/Authors/AuthorsStats.dashboard?ns=COMMUNITY&embed=1
After running the filter with no rows it turns listing mode on and shows no data forever.
![lptlistingbug2](https://user-images.githubusercontent.com/2781759/28497465-93b39364-6f90-11e7-8a84-53250524dbe0.gif)

**Comment by nikitaeverywhere** [comment] 2017-07-23 15:56
Thanks Evgeny! Will look at this issues on the next week, I'm currently out for a while.

**Comment by nikitaeverywhere** [comment] 2017-07-29 11:44
Regarding to (1), it is most likely DSW issue. Technically, when the filter is set, DSW triggers `changeBasicMDX` method of LPT. See what I was able to debug:

![2017-07-29_143641](https://user-images.githubusercontent.com/4989256/28744552-35b1d5a6-746c-11e7-8c29-41d7e01f3797.png)
![2017-07-29_144024](https://user-images.githubusercontent.com/4989256/28744553-3c756fa6-746c-11e7-9dde-301b021dce31.png)

And now if I uncheck all, the MDX gets magically changed to `DRILLTHROUGH`:

![2017-07-29_143911](https://user-images.githubusercontent.com/4989256/28744566-5952ed10-746c-11e7-804a-4f0c848d4ab6.png)

Which gives the exact result you demonstrated.

**Comment by nikitaeverywhere** [comment] 2017-07-29 11:45
P.S. Special thanks for the GIFs! :)

**Comment by nikitaeverywhere** [comment] 2017-07-29 11:50
I see the same issue with (2):

![2017-07-29_144726](https://user-images.githubusercontent.com/4989256/28744612-325567a0-746d-11e7-92ea-d30484e735f9.png)
![2017-07-29_144820](https://user-images.githubusercontent.com/4989256/28744613-3255c1aa-746d-11e7-9361-cdaaff4159b5.png)

The incoming MDX changes to `DRILLTHROUGH`.

**Comment by nikitaeverywhere** [comment] 2018-03-18 16:51
Closing as duplicate of #14.

**Closed as completed by nikitaeverywhere** 2018-03-18 16:51 UTC
